prefix           = File.dirname( __FILE__ )
sstoolkit        = File.join(prefix, '../')
output_dir       = File.join(prefix, 'Output')
doxygen_config   = File.join(prefix, 'Doxygen/doxygen.config')
doxyclean        = File.join(prefix, 'Doxygen/doxyclean.py')
gemfile          = File.join(prefix, 'Gemfile')
sass_dir         = File.join(prefix, 'scss')
temp_dir         = File.join(prefix, 'temp')
css_dir          = File.join(temp_dir, 'css')
compass_options  = "--sass-dir #{sass_dir} --css-dir #{css_dir} --output-style compressed"

task :default => :all

desc 'Clean, build, and reformat docs'
task :all => [:clean, :build, :reformat] do
  puts "Done!"
end

desc 'Remove all generated documentation'
task :clean do
  system "rm -rf #{temp_dir} #{output_dir}"
end

desc 'Build the documentation with Doxygen'
task :build => [temp_dir] do
  system "cd #{prefix}; doxygen #{doxygen_config}"
end

desc 'Reformat documentation with Doxyclean'
task :reformat => :compass do
  system "rm -rf #{output_dir}"
  system "python #{doxyclean} --phone --input=#{temp_dir}/xml --output=#{temp_dir}/doxyclean --name=SSToolkit"
  system "mv #{temp_dir}/doxyclean/html #{output_dir}"
end


desc 'Open the generated documentation in default browser'
task :open do
  system "open #{output_dir}/index.html"
end

desc 'Rebuild, format, and open'
task :'rebuild:open' => [:clean, :build, :reformat, :open]

# Bundler
desc 'Run Bundler and install gems'
task :bundle do
  # Check for Bundler
  require 'rubygems'
  begin
    require 'bundler'
  rescue LoadError
    puts 'You must `gem install bundler` to run rake tasks' and return
  end
  
  # puts 'Updating gems...'
  system "bundle install --gemfile=#{gemfile} --quiet"
end

desc 'Build Compass output'
task :compass => [:bundle, temp_dir, :'compass:clean'] do
  system "export BUNDLE_GEMFILE=#{gemfile}; bundle exec compass compile #{compass_options} --boring --quiet"
end

namespace :compass do
  desc 'Clean Compass output'
  task :clean do
    system "rm -rf #{css_dir}"
  end
  
  desc 'Start Compass watching the stylesheets directory'
  task :watch => [:'compass:clean'] do
    system "BUNDLE_GEMFILE=#{gemfile}; bundle exec compass watch #{compass_options}"
  end
end

directory temp_dir
